<%@ Page Title="" Language="C#" UnobtrusiveValidationMode="None" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="EquipoLaboratorio.aspx.cs" Inherits="Inventario.EquipoLaboratorio" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="article">
        <h2><span><asp:Label ID="LabelProductos" runat="server" Visible="false" Text="EQUIPO DE LABORATORIO"></asp:Label></span></h2> 
    </div>
     <asp:DropDownList id="ddlSedes" AutoPostBack="True" runat="server" OnSelectedIndexChanged = "OnSelectedIndexChanged" BackColor="#192666" ForeColor="#F0F3F4">

                    <asp:ListItem Selected="True" Value="Inicio" > seleccione una sede</asp:ListItem>
                  <asp:ListItem Value="Central"> Campus Central </asp:ListItem>
                  <asp:ListItem Value="Zacapa"> Zacapa </asp:ListItem>
                    <asp:ListItem Value="Escuintla"> Escuintla </asp:ListItem>
                     <asp:ListItem Value="Quetzal"> Quetzaltenango </asp:ListItem>
                     <asp:ListItem Value="Verapaz"> Verapaz </asp:ListItem>
                     <asp:ListItem Value="Huehue"> Huehuetenango </asp:ListItem>

     </asp:DropDownList>

     <asp:GridView ID="DataProducto" runat="server" AutoGenerateColumns="False" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
            BorderWidth="1px">
         <Columns>


            <asp:BoundField DataField="ID" HeaderText="ID" ReadOnly="true"/>
            <asp:BoundField DataField="Ubicacion" HeaderText="Ubicacion" ReadOnly="true" />
             <asp:BoundField DataField="Serie" HeaderText="Serie" ReadOnly="true" />
            <asp:BoundField DataField="Descripcion" HeaderText="Descripcion" />
            <asp:BoundField DataField="Estado" HeaderText="Estado" />
            <asp:BoundField DataField="Renovacion" HeaderText="Renovacion" />
            

         </Columns>
    </asp:GridView>

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />


</asp:Content>



