<%@ Page Title="" Language="C#" UnobtrusiveValidationMode="None" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="EquipoLaboratorio2.aspx.cs" Inherits="Inventario.EquipoLaboratorio2" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="article">
        <h2><span><asp:Label ID="LabelProductos" runat="server" Visible="false" Text="EQUIPO DE LABORATORIO"></asp:Label></span></h2> 
    </div>
     <asp:DropDownList id="ddlSedes" AutoPostBack="True" runat="server" OnSelectedIndexChanged = "OnSelectedIndexChanged" BackColor="#192666" ForeColor="#F0F3F4">

     </asp:DropDownList>

    <%-- <asp:DropDownList ID="ddlLaboratorios" runat="server">

    </asp:DropDownList>
        --%>
     <asp:GridView ID="DataProducto" runat="server" AutoGenerateColumns="False" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" 
            BorderWidth="1px">
         <Columns>

             <%-- 
            <asp:BoundField DataField="ID" HeaderText="ID" ReadOnly="true"/>
            <asp:BoundField DataField="Ubicacion" HeaderText="Ubicacion" ReadOnly="true" />
             <asp:BoundField DataField="Serie" HeaderText="Serie" ReadOnly="true" />
            <asp:BoundField DataField="Descripcion" HeaderText="Descripcion" />
            <asp:BoundField DataField="Estado" HeaderText="Estado" />
            <asp:BoundField DataField="Renovacion" HeaderText="Renovacion" />
--%>

             <asp:BoundField DataField="ID" HeaderText="ID"/>
            <asp:BoundField DataField="Ubicacion" HeaderText="Ubicacion" />
             <asp:BoundField DataField="Serie" HeaderText="Serie"/>
            <asp:BoundField DataField="Descripcion" HeaderText="Descripcion" />
           <%--  <asp:BoundField DataField="Estado" HeaderText="Estado" /> --%>

            <asp:TemplateField HeaderText="Estado">
		    <EditItemTemplate>
			<asp:DropDownList ID="ddl_estado" runat="server">
			</asp:DropDownList>
		    </EditItemTemplate>
		    <ItemTemplate>
			<asp:Label ID="Label4" runat="server" Text='<%# Eval("Estado") %>'></asp:Label>
		    </ItemTemplate>
	        </asp:TemplateField>

             <asp:TemplateField HeaderText="Renovacion">
		    <EditItemTemplate>
			<asp:DropDownList ID="ddl_renovacion" runat="server">
			</asp:DropDownList>
		    </EditItemTemplate>
		    <ItemTemplate>
			<asp:Label ID="Label5" runat="server" Text='<%# Eval("Renovacion") %>'></asp:Label>
		    </ItemTemplate>
	        </asp:TemplateField>

             <%--<asp:BoundField DataField="Renovacion" HeaderText="Renovacion" />--%>
            

         </Columns>
    </asp:GridView>

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />


</asp:Content>



